name: CI/CD Pipeline to EC2

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        if [ -d "tests" ]; then
          pytest
        else
          echo "No tests directory found."
        fi

    - name: Add SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_KEY }}

    - name: Deploy to EC2
      env:
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_USER: ${{ secrets.EC2_USER }}
      run: |
        echo "Deploying application to EC2 instance at $EC2_HOST"
        ssh -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST << 'EOF'
          # Pull latest code or clone if folder doesn't exist
          cd /home/$EC2_USER/app || mkdir -p /home/$EC2_USER/app && cd /home/$EC2_USER/app
          git pull origin main

          # Build and run Docker container
          docker build -f Dockerfile.dockerfile -t my-app .
          docker stop my-app || true
          docker rm my-app || true
          docker run -d --name my-app -p 80:5000 my-app
        EOF
